name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Get Credentials
      env:
        CLOUDKIT_KEY_BASE64: ${{ secrets.CLOUDKIT_KEY_BASE64 }}
      run: |
        CLOUDKIT_KEY_PATH=$RUNNER_TEMP/key.pem
        echo -n "$CLOUDKIT_KEY_BASE64" | base64 --decode --output $CLOUDKIT_KEY_PATH

    - name: Build
      run: swift build -v

    - name: Validate
      env:
        CLOUDKIT_KEY_ID: ${{ secrets.CLOUDKIT_KEY_ID }}
      run: |
        for file in `git diff --name-only --diff-filter=A HEAD^`; do
          if [[ "$file" != pending/* ]]; then
            continue
          fi
          id=${file##pending/}
          .build/debug/CelestiaAddonValidatorApp $RUNNER_TEMP/key.pem $CLOUDKIT_KEY_ID $id
        done

    - name: Upload
      if: github.event_name != 'pull_request'
      env:
        CLOUDKIT_KEY_ID: ${{ secrets.CLOUDKIT_KEY_ID }}
      run: |
        for file in `git diff --name-only --diff-filter=A HEAD^`; do
          if [[ "$file" != pending/* ]]; then
            continue
          fi
          id=${file##pending/}
          .build/debug/CelestiaAddonValidatorApp --upload $RUNNER_TEMP/key.pem $CLOUDKIT_KEY_ID $id
          git rm pending/$id
        done

    - name: Clean Up
      if: github.event_name != 'pull_request' && always()
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -m "Cleaning up"
          git push -f
        fi
